// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Student struct {
	StudentID      int32
	FirstName      string
	LastName       string
	Email          string
	EnrollmentDate pgtype.Date
}
